# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
# CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=10
# CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
# CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=42

# CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=2500
# CONFIG_INPUT_LOG_LEVEL_DBG=y
# CONFIG_I2C_LOG_LEVEL_DBG=y
